/**
 * Types for the toolkit manifest generated by scripts/transform-toolkit-structure.ts
 */

export interface Agent {
  slug: string;
  name: string;
  description: string;
  mode: 'primary' | 'subagent';
  category: 'critics' | 'developers' | 'testers' | 'orchestrators' | 'utilities';
  content: string;
}

export type SkillCategory = 'workflow' | 'content' | 'project' | 'meta' | 'utilities';

export interface Skill {
  slug: string;
  name: string;
  description: string;
  triggers: string[];
  isMeta: boolean;
  category?: SkillCategory;
  content: string;
}

export interface Scaffold {
  slug: string;
  name: string;
  description: string;
  files: string[];
}

export interface AgentTemplate {
  slug: string;
  name: string;
  description: string;
  category: string;
  appliesTo: string[];
  generates: string;
  content: string;
}

export type ChangelogEntryType = 'feat' | 'fix' | 'chore' | 'docs' | 'refactor' | 'test' | 'style' | 'perf' | 'ci' | 'build';

export type ChangelogSource = 'toolkit' | 'website';

export interface ChangelogEntry {
  type: ChangelogEntryType;
  description: string;
  scope?: string;
}

export interface ChangelogEntryWithSource extends ChangelogEntry {
  source: ChangelogSource;
}

export interface ChangelogDay {
  date: string;
  displayDate: string;
  changes: ChangelogEntry[];
}

export interface ChangelogDayWithSource {
  date: string;
  displayDate: string;
  changes: ChangelogEntryWithSource[];
}

/**
 * Build-time changelog output format (from scripts/sync-changelog.ts)
 */
export interface ChangelogOutput {
  generatedAt: string;
  sources: {
    toolkit: {
      fetched: boolean;
      commitCount: number;
      error?: string;
    };
    website: {
      fetched: boolean;
      commitCount: number;
      error?: string;
      tokenAvailable: boolean;
    };
  };
  changelog: ChangelogDayWithSource[];
}

export interface ToolkitManifest {
  version: string;
  generatedAt: string;
  syncedAt: string;
  toolkitCommit: string;
  counts: {
    agents: number;
    primaryAgents: number;
    subagents: number;
    skills: number;
    metaSkills: number;
    scaffolds: number;
    agentTemplates: number;
  };
  categories: {
    critics: number;
    developers: number;
    testers: number;
    orchestrators: number;
    utilities: number;
  };
  skillCategories?: {
    workflow: number;
    content: number;
    project: number;
    meta: number;
    utilities: number;
  };
  templateCategories: string[];
  agents: Agent[];
  skills: Skill[];
  scaffolds: Scaffold[];
  agentTemplates: AgentTemplate[];
  changelog: ChangelogDay[];
}
