/**
 * Types for the toolkit manifest generated by scripts/extract-toolkit-data.ts
 */

export interface Agent {
  slug: string;
  name: string;
  description: string;
  mode: 'primary' | 'subagent';
  category: 'critics' | 'developers' | 'testers' | 'other';
  content: string;
}

export interface Skill {
  slug: string;
  name: string;
  description: string;
  triggers: string[];
  isMeta: boolean;
  content: string;
}

export interface Scaffold {
  slug: string;
  name: string;
  description: string;
  files: string[];
}

export interface AgentTemplate {
  slug: string;
  name: string;
  description: string;
  category: string;
  appliesTo: string[];
  generates: string;
  content: string;
}

export interface ChangelogEntry {
  type: 'feat' | 'fix' | 'refactor' | 'docs' | 'chore';
  description: string;
  scope?: string;
}

export interface ChangelogDay {
  date: string;
  displayDate: string;
  changes: ChangelogEntry[];
}

export interface ToolkitManifest {
  generatedAt: string;
  counts: {
    agents: number;
    primaryAgents: number;
    subagents: number;
    skills: number;
    metaSkills: number;
    scaffolds: number;
    agentTemplates: number;
  };
  categories: {
    critics: number;
    developers: number;
    testers: number;
    other: number;
  };
  templateCategories: string[];
  agents: Agent[];
  skills: Skill[];
  scaffolds: Scaffold[];
  agentTemplates: AgentTemplate[];
  changelog: ChangelogDay[];
}
